### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by xRedFox** [TeaSpeak/TeaSpeak#243]
**Describe the bug**

- *TeaSpeak*:
```
[2018-07-27 14:26:45] [DEBUG]   GEN | Loaded client from database. Database id: 2 Unique id: UnknownQuery
[2018-07-27 14:26:45] [INFO]  QUERY | Got new client from 5.152.140.132:48354
[2018-07-27 14:26:45] [ERROR]   GEN | Query ssl error: Could not proceed accept! (-2|1)
[2018-07-27 14:27:15] [ERROR] QUERY | [5.152.140.132:48354/ServerQuery#5.152.140.132/48354] Failed to read! Code: 0 errno: 0 message: Success
```
*or from localhost*
```
[2018-07-27 13:43:18] [DEBUG]   GEN | Loaded client from database. Database id: 2 Unique id: UnknownQuery
[2018-07-27 13:43:18] [INFO]  QUERY | Got new client from 127.0.0.1:47306
[2018-07-27 13:43:18] [ERROR]   GEN | Query ssl error: Could not proceed accept! (-2|1)
```

- *PHP*:
```
Warning: stream_socket_enable_crypto(): SSL: Handshake timed out in C:\Users\redfox\Repos\TeamSpeak3Panel\core\TeamSpeak3\Transport\TCP.php on line 57
TeamSpeak3_Transport_Exception: connection to server '79.143.183.2:10101' lost in C:\Users\redfox\Repos\TeamSpeak3Panel\core\TeamSpeak3\Transport\TCP.php:131 Stack trace: #0 C:\Users\redfox\Repos\TeamSpeak3Panel\core\TeamSpeak3\Adapter\ServerQuery.php(73): TeamSpeak3_Transport_TCP->readLine() #1 C:\Users\redfox\Repos\TeamSpeak3Panel\core\TeamSpeak3\Adapter\Abstract.php(57): TeamSpeak3_Adapter_ServerQuery->syn() #2 C:\Users\redfox\Repos\TeamSpeak3Panel\core\TeamSpeak3\TeamSpeak3.php(327): TeamSpeak3_Adapter_Abstract->__construct(Array) #3 C:\Users\redfox\Repos\TeamSpeak3Panel\core\TsQuery.php(33): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri)) #4 C:\Users\redfox\Repos\TeamSpeak3Panel\panel.php(30): TsQuery->connectToServer() #5 {main}
```

**To Reproduce**
Steps to reproduce the behaviour:
https://github.com/planetteamspeak/ts3phpframework
```
[...]

$serverquery = "serverquery://$serverQueryUser:$serverQueryPasw@$host:$serverQueryPort/?tls=1";
$server = TeamSpeak3::factory($serverquery);

[...]
```

**Expected behaviour**
you know :)

**Logs**
[log_2018-07-27_09_31_54_general.log](https://github.com/TeaSpeak/TeaSpeak/files/2235744/log_2018-07-27_09_31_54_general.log)

**Environment information:**
 Operating system: 4.17.5-1-ARCH x86_64 GNU/Linux
 TeaSpeak version: TeaSpeak-1.1.41-beta-2

**Additional context**
????????????
??? #221 ???
????????????

**Comment by WolverinDEV** [comment]
Hmm that's a quite interesting error.
I already saw that once, but it disappeared by updating (or changing) the SSL library.

This needs some inspection! (I'll do this after vacation)

**Comment by WolverinDEV** [comment]
Should be fixed :) (Not 100% sure but for me it works)

**Comment by xRedFox** [comment]
@WolverinDEV 
Yep i can confirm. It works better than before hehe!

One more thing, i don't want to open another issue for this, in the latest version the `Starting server. [Starting default server]` doesn't disappear, please adjust this little thing.

Love you man ❤️
