### ISSUE TITLE
Can't run TeaClient

### ISSUE THREAD

**Issue by peylight** [TeaSpeak/TeaSpeak#489]
Hi
I have kubuntu 18.04 and i installed TeaClient.
After execute to run TeaClient I see a Loading popup and then disappeared...
The console log is this:

```
$ TeaClient 

(TeaClient:5875): Gtk-WARNING **: 07:13:08.869: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(TeaClient:5875): Gtk-WARNING **: 07:13:08.869: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(TeaClient:5875): Gtk-WARNING **: 07:13:08.869: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Main app executed!
Spawn loading screen
Spawn window!
request: http://clientapi.teaspeak.de//api.php?type=update-info
Loading ui package
TypeError: Cannot read property 'body' of undefined
    at Request.request.get [as _callback] (/usr/lib/TeaClient/resources/app.asar/updater/updater.js:129:38)
    at self.callback (/usr/lib/TeaClient/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at ClientRequest.<anonymous> (/usr/lib/TeaClient/resources/app.asar/node_modules/request/request.js:819:16)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.emitTimeout (_http_client.js:706:34)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:445:8) 'Uncaught Exception thrown'
TypeError: Cannot read property 'body' of undefined
    at Request.request.get [as _callback] (/usr/lib/TeaClient/resources/app.asar/updater/updater.js:129:38)
    at self.callback (/usr/lib/TeaClient/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at ClientRequest.<anonymous> (/usr/lib/TeaClient/resources/app.asar/node_modules/request/request.js:819:16)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.emitTimeout (_http_client.js:706:34)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:445:8)
```

**Comment by WolverinDEV** [comment]
Which version are you using?
It seems like a request fails for update checking and the eroor isn't handled properly.
